C NATHAN DILL
C 7-21-07
C THIS PROGRAM READS THE OUT.XYZ FILE GENERATED BY MAUREPARTICLE, 
C SORTs IT BY PARTICLE ID, AND ALLOWS YOU TO WRITE OUT PARTICLE TRACKS FOR
C INDIVIDUAL PARTICLES IN SEPARATE FILES. IT WILL TELL YOU HOW MANY PARTICLES
C AND HOW MANY RECORDS THERE ARE IN THE OUT.XYZ
C______________________________________________________________________
C======================================================================
      PROGRAM PART_SORT
C----------------------------------------------------------------------      
      IMPLICIT NONE
      
      INTEGER I,J,K,NP,J1,J2,PID,CNT
      REAL*8, ALLOCATABLE :: X(:,:),Y(:,:),T(:,:)
      REAL*8  A,B
      CHARACTER*50 FILENAME
C----------------------------------------------------------------------      
CC      WRITE(*,*)'hOW mANY pARTICLES?'
CC      WRITE(*,*)
CC      READ(*,*)NP
CC      WRITE(*,*)'hOW mANY oUTPUT sTEPS?'
CC      WRITE(*,*)
CC      READ(*,*)K
      OPEN(UNIT=11,FILE='OUT.XYZ')
      
      NP=-1
      CNT=0
      DO WHILE(.TRUE.)
         NP=NP+1
         READ(11,*)A,B,J1,PID
         IF (PID.EQ.1.AND.CNT.EQ.1) GOTO 5
         IF (PID.EQ.1) CNT=CNT+1
      END DO
   
 5    CLOSE(11)
      
      OPEN(UNIT=11,FILE='OUT.XYZ')
                 
      CNT=0
      DO WHILE(.TRUE.)
         READ(11,*,END=10)
         CNT=CNT+1
      END DO
 10   CLOSE(11)
      
      CNT=INT(CNT/NP)
      
      WRITE(*,*)'tHERE aRE ',NP,' pARTICLES aND ',CNT,' rECORDS'
      WRITE(*,*)
      
      
      
      ALLOCATE ( X(CNT,NP),Y(CNT,NP),T(CNT,NP) )
      
      OPEN(UNIT=11,FILE='OUT.XYZ')
      

      DO I=1,CNT
         DO J=1,NP
            READ(11,*,END=50)X(I,J),Y(I,J),J1,J2,T(I,J)
         END DO
      END DO
          
 50   CLOSE(11)
      
 100  CONTINUE
      WRITE(*,*)'wHICH pARTICLE dO yOU wANT?'
      WRITE(*,*)
      READ(*,*)PID  
      WRITE(*,*)'fILENAME fOR oUTPUT?'
      WRITE(*,*)
      READ(*,*)FILENAME
       
      OPEN(UNIT=12,FILE=FILENAME)
      
      DO I=1,CNT
         WRITE(12,*)X(I,PID),Y(I,PID),T(I,PID)
      END DO
      CLOSE(12)
      
      WRITE(*,*)TRIM(FILENAME),' wRITTEN' 
      WRITE(*,*)
      WRITE(*,*)'mAKE aNOTHER (yES=1,nO=0)?'
      WRITE(*,*)
      READ(*,*)J
      
      
      IF (J.EQ.1) GOTO 100
     
      
      END PROGRAM